# Site settings
title: ELIXIR Beacon Network Documentation
author:
  name: Sergi Aguiló Castillo9
  email: sergi.aguilo@bsc.es
description: "ELIXIR Beacon Network current documentation. This pages are a living document of the current documentation of this development"

# Build settings
remote_theme: "pmarsceill/just-the-docs"
# Configure Just the Docs settings
just_the_docs:
  search_enabled: true
  show_last_updated: true
  collections:
    nav:
      - title: "Documentation"
        url: "/docs/governanceModel"
        children